CREATE DATABASE HEALTHCARE_ANALYTICS;
USE HEALTHCARE_ANALYTICS;

#DATA CLEANING PROCESS:

ALTER TABLE APPOINTMENTS
MODIFY APPOINTMENT_DATE DATE;

ALTER TABLE APPOINTMENTS
MODIFY VISIT_TYPE VARCHAR(20);

ALTER TABLE APPOINTMENTS
MODIFY STATUS VARCHAR(20);

SET SQL_SAFE_UPDATES = 0;

UPDATE BILLING
SET BILLING_DATE = STR_TO_DATE(BILLING_DATE, '%d-%m-%Y');

ALTER TABLE BILLING
MODIFY BILLING_DATE DATE;

ALTER TABLE TREATMENT
MODIFY TREATMENT_TYPE VARCHAR(20);