CREATE DATABASE HEALTHCARE_ANALYTICS;
USE HEALTHCARE_ANALYTICS;

#DATA CLEANING PROCESS:

SELECT * FROM PATIENTS WHERE PATIENTS_ID IS NULL OR AGE IS NULL;
SELECT * FROM DOCTORS WHERE DEPARTMENT IS NULL;
SELECT * FROM APPOINTMENTS WHERE APPOINTMENT_DATE IS NULL;
SELECT * FROM BILLING WHERE AMOUNT_PAID IS NULL;


#CHECK DUPLICATES

SELECT PATIENT_ID, COUNT(*) 
FROM PATIENTS
GROUP BY PATIENT_ID
HAVING COUNT(*) > 1;

SELECT DOCTOR_ID, COUNT(*) 
FROM DOCTORS
GROUP BY DOCTOR_ID
HAVING COUNT(*) > 1;

SELECT APPOINTMENT_ID, COUNT(*) 
FROM APPOINTMENTS
GROUP BY APPOINTMENT_ID
HAVING COUNT(*) > 1;

SELECT TREATMENT_ID, COUNT(*) 
FROM TREATMENT
GROUP BY TREATMENT_ID
HAVING COUNT(*) > 1;

SELECT BILLING_ID, COUNT(*) 
FROM BILLING
GROUP BY BILLING_ID
HAVING COUNT(*) > 1;


#HANDLE NULL VALUES:

UPDATE PATIENTS
SET CITY = 'UNKNOWN'
WHERE CITY IS NULL;

UPDATE DOCTORS
SET DEPARTMENT = 'GENERAL'
WHERE DEPARTMENT IS NULL;


#REMOVE INVALID RECORDS

DELETE FROM BILLING
WHERE AMOUNT_PAID < 0;

------------#EXECUTIVE OVERVIEW---

#1. TOTAL NUMBERS OF PATIENTS:

SELECT COUNT(*) AS TOTAL_PATIENTS FROM PATIENTS;

#2.TOTAL NUMBERS OF DOCTORS:

SELECT COUNT(*) AS TOTAL_DOCTORS FROM DOCTORS;

#3.TOTAL NUMBERS OF APPOINTMENTS:

SELECT COUNT(*) AS TOTAL_APPOINTMENTS FROM APPOINTMENTS;

#4.TOTAL REVENUE:

SELECT
    SUM(B.AMOUNT_PAID)AS TOTAL_REVENUE
FROM BILLING B;

#5.AVERAGE BILL AMOUNT:

SELECT AVG(AMOUNT_PAID) AS AVERAGE_BILL_AMOUNT FROM BILLING;


#6.MONTHLY APPOINTMENTS:

SELECT 
   DATE_FORMAT(MIN(APPOINTMENT_DATE), '%m-%Y') AS APPOINTMENT_MONTH,
   COUNT(APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
FROM APPOINTMENTS
GROUP BY 
   YEAR(APPOINTMENT_DATE),
   MONTH(APPOINTMENT_DATE)
ORDER BY 
   YEAR(APPOINTMENT_DATE),
   MONTH(APPOINTMENT_DATE);

   
#7.MONTHLY REVENUE:

SELECT 
   DATE_FORMAT(BILLING_DATE, '%Y-%m') AS BILLING_MONTH,
   SUM(AMOUNT_PAID) AS TOTAL_REVENUE
FROM BILLING
GROUP BY BILLING_MONTH
ORDER BY BILLING_MONTH;
   
   
#8.APPOINTMENT STATUS:

SELECT
    STATUS,
    COUNT(APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
FROM APPOINTMENTS
GROUP BY STATUS;

#9.DEPARTMENT REVENUE:

SELECT 
    D.DEPARTMENT AS DEPARTMENT,
    SUM(B.AMOUNT_PAID) AS TOTAL_REVENUE 
FROM DOCTORS D
JOIN APPOINTMENTS A 
ON D.DOCTOR_ID = A.DOCTOR_ID
JOIN BILLING B 
ON A.APPOINTMENT_ID = B.APPOINTMENT_ID  
GROUP BY DEPARTMENT;
    
------------#PATIENT ANALYSIS---

#1.PATIENT COUNT BY CITY:

SELECT 
    CITY,
    COUNT(PATIENT_ID) AS TOTAL_PATIENTS
FROM PATIENTS
GROUP BY CITY
ORDER BY TOTAL_PATIENTS;
    

#2.GENDER DISTRIBUTION:

SELECT
    GENDER,
    COUNT(PATIENT_ID) AS TOTAL_PATIENTS
FROM PATIENTS
GROUP BY GENDER;


#3.TOP 10 FREQUANTLY VISITING PATIENTS:

SELECT 
    P.PATIENT_ID,
    P.PATIENT_NAME,
    COUNT(A.APPOINTMENT_ID) AS TOTAL_VISIT
FROM PATIENTS P
JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
GROUP BY
    P.PATIENT_ID,
    P.PATIENT_NAME
ORDER BY
    TOTAL_VISIT DESC
LIMIT 10;


#4.REPEAT VISIT RATE:

SELECT
    CONCAT(
        ROUND(
          COUNT(*) * 100/
          (SELECT COUNT(PATIENT_ID) FROM PATIENTS)
		 ),'%')AS REPEAT_VISIT_RATE_PERCENT
FROM (
	SELECT PATIENT_ID
    FROM APPOINTMENTS
    GROUP BY PATIENT_ID
    HAVING COUNT(APPOINTMENT_ID) >1
     ) REPEAT_PATIENTS;
     
     
#5.AGE GROUP DISTRIBUTION:

SELECT
    CASE
        WHEN AGE BETWEEN 0 AND 18 THEN '0-18'
        WHEN AGE BETWEEN 19 AND 35 THEN '19-35'
        WHEN AGE BETWEEN 36 AND 50 THEN '36-50'
        WHEN AGE BETWEEN 51 AND 65 THEN '51-65'
        ELSE '66+'
    END AS AGE_GROUP,
    COUNT(DISTINCT PATIENT_ID) AS TOTAL_PATIENTS
FROM PATIENTS
GROUP BY AGE_GROUP
ORDER BY AGE_GROUP ASC;


#6.AVERAGE PATIENT AGE:

SELECT
    CONCAT(ROUND(AVG(AGE), 2),'%') AS AVERAGE_PATIENT_AGE
FROM PATIENTS
WHERE AGE IS NOT NULL;

    
-----------#DOCTOR PERFORMANCE---

#1.APPOINTMENTS BY DOCTOR:

SELECT 
   D.DOCTOR_ID,
   D.DOCTOR_NAME,
   COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
FROM DOCTORS D
JOIN APPOINTMENTS A 
ON D.DOCTOR_ID = A.DOCTOR_ID
GROUP BY 
   D.DOCTOR_ID,
   D.DOCTOR_NAME
ORDER BY
   D.DOCTOR_ID;


#2.REVENUE BY DOCTOR:

SELECT
   D.DOCTOR_ID,
   D.DOCTOR_NAME,
   SUM(B.AMOUNT_PAID) AS TOTAL_REVENUE
FROM DOCTORS D
JOIN APPOINTMENTS A
ON D.DOCTOR_ID = A.DOCTOR_ID
JOIN BILLING B
ON A.APPOINTMENT_ID = B.APPOINTMENT_ID
GROUP BY 
   D.DOCTOR_ID,
   D.DOCTOR_NAME
ORDER BY D.DOCTOR_ID;


#3.DOCTOR VS DEPARTMENT:

SELECT
	DEPARTMENT,
    COUNT(DISTINCT DOCTOR_ID) AS TOTAL_DOCTORS
FROM DOCTORS
GROUP BY DEPARTMENT
ORDER BY TOTAL_DOCTORS DESC;


#4.AVERAGE REVENUE PER DOCTOR

SELECT
   ROUND(SUM(B.AMOUNT_PAID)/COUNT(D.DOCTOR_ID),2) AS AVERAGE_REVENUE_PER_DOCTOR
FROM DOCTORS D
JOIN APPOINTMENTS A
ON D.DOCTOR_ID = A.DOCTOR_ID
JOIN BILLING B
ON A.APPOINTMENT_ID = B.APPOINTMENT_ID;


#5.AVERAGE APPOINTMENTS PER DOCTOR:

SELECT
    ROUND(COUNT(A.APPOINTMENT_ID) *1.0
    / COUNT(DISTINCT D.DOCTOR_ID),2) AS AVG_APPOINTMENTS_PER_DOCTOR
FROM DOCTORS D
LEFT JOIN APPOINTMENTS A
ON D.DOCTOR_ID = A.DOCTOR_ID;


------------#APPOINTMENT ANALYSIS---

#1.APPOINTMENTS BY DAY OF WEEK:

SELECT
    DAYNAME(APPOINTMENT_DATE) AS DAY_OF_WEEK,
    COUNT(APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
FROM APPOINTMENTS
GROUP BY DAY_OF_WEEK
ORDER BY
    FIELD(DAY_OF_WEEK,
    'MONDAY','TUESDAY','WEDNESDAY','THURSDAY',
    'FRIDAY','SATURDAY','SUNDAY');
    
#2.APPOINTMENT STATUS:

SELECT
    STATUS AS APPOINTMENT_STATUS,
    COUNT(APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
FROM APPOINTMENTS
GROUP BY STATUS
ORDER BY TOTAL_APPOINTMENTS DESC;

#3.COMPLETION RATE:

SELECT
    CONCAT(
       ROUND(
		  SUM(CASE WHEN STATUS = 'COMPLETED' THEN 1 ELSE 0 END) *100
          / COUNT(APPOINTMENT_ID),
          2
            ),'%'
         )AS COMPLITION_RATE_PERCENT
FROM APPOINTMENTS;

#4.CANCELLATION RATE:

SELECT
    CONCAT(
       ROUND(
		  SUM(CASE WHEN STATUS = 'CANCELLED' THEN 1 ELSE 0 END) *100
          / COUNT(APPOINTMENT_ID),
          2
            ),'%'
         )AS CANCELLATION_RATE_PERCENT
FROM APPOINTMENTS;


-------------#TREATMENT & DIAGNOSIS ANALYSIS---

#1.REVENUE BY DIAGNOSIS:

SELECT
   T.TREATMENT_TYPE AS DIAGNOSIS,
   SUM(B.AMOUNT_PAID) AS TOTAL_REVENUE
FROM TREATMENT T
JOIN BILLING B
ON T.APPOINTMENT_ID = B.APPOINTMENT_ID
GROUP BY DIAGNOSIS
ORDER BY TOTAL_REVENUE DESC;


#2.AVERAGE TREATMENT COST:

SELECT
    TREATMENT_TYPE AS DIAGNOSIS,
    ROUND(AVG(B.AMOUNT_PAID), 2) AS AVG_TREATMENT_COST
FROM TREATMENT T
JOIN BILLING B
ON T.APPOINTMENT_ID = B.APPOINTMENT_ID
GROUP BY DIAGNOSIS
ORDER BY AVG_TREATMENT_COST DESC;


#3.TREATMENTS ARE PROVIDED PER DIAGNOSIS:

SELECT
    TREATMENT_TYPE AS DIAGNOSIS,
    COUNT(TREATMENT_ID) AS TOTAL_TREATMENTS
FROM TREATMENT
GROUP BY DIAGNOSIS
ORDER BY TOTAL_TREATMENTS DESC;


------------#BILLING & REVENUE---

#1.MONTHLY REVENUE:

SELECT 
    DATE_FORMAT(BILLING_DATE, '%Y-%m') AS DATE,
    SUM(AMOUNT_PAID) AS REVENUE
FROM BILLING 
GROUP BY DATE
ORDER BY DATE;


#2.REVENUE BY CITY:

SELECT 
   P.CITY,
   SUM(B.AMOUNT_PAID) AS REVENUE
FROM PATIENTS P
JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
JOIN BILLING B 
ON A.APPOINTMENT_ID = B.APPOINTMENT_ID
GROUP BY CITY
ORDER BY CITY;


#3.REVENUE BY PAYMENT MODE:

SELECT
   PAYMENT_MODE,
   SUM(AMOUNT_PAID) AS REVENUE
FROM BILLING
GROUP BY PAYMENT_MODE
ORDER BY REVENUE;

#4.TOTAL REVENUE:

SELECT
    SUM(B.AMOUNT_PAID)AS TOTAL_REVENUE
FROM BILLING B;


 
   
   


















